### ISSUE TITLE
compatibility with SCXML files

### ISSUE THREAD

**Issue by edbek** [dziegel/cpp_statemachine_generator#1]
I tried generating state machines SCXML via state charts (https://github.com/sverweij/state-machine-cat), but your C++ statemachine generator fails when trying to generate *.hpp files in the ./genarated directory.

Does yours have compatibility with SCXML files?

**Comment by dziegel** [comment]
The generator can handle SCXML as stated in the description. Tested with QtCreator. From your report, I don't get any clue what goes wrong, can you share more info?

**Comment by edbek** [comment]
here is a draft of the SCXML file: 

<?xml version="1.0" encoding="UTF-8"?>
<scxml xmlns="http://www.w3.org/2005/07/scxml" initial="_fork.1" version="1.0">
    <state id="_fork.1">
        <transition target="thing"/>
        <transition target="second.thing"/>
        <transition target="thing1"/>
    </state>
    <state id="_junction.1">
        <transition target="final"/>
    </state>
    <parallel id="bla.parallel">
        <state id="first">
            <state id="thing">
                <transition target="first.thang"/>
            </state>
            <state id="first.thang">
                <transition target="_junction.1"/>
            </state>
        </state>
        <state id="first2">
            <state id="thing1">
                <transition target="thing2"/>
                <transition target="first2.thang"/>
            </state>
            <state id="thing2" initial="Bound2">
                <history id="NormalMode2.history">
                </history>
                <state id="Bound2">
                    <onentry>dhcp_set_timers</onentry>
                    <onentry>dhcp_display_result</onentry>
                    <transition event="T1" target="Renewing2"/>
                    <transition event="10s" target="Renewing2"/>
                    <transition event="DHCPOFFER DHCPACK DHCPNACK" target="Bound2"/>
                </state>
                <state id="Renewing2">
                    <onentry>dhcp_send_request</onentry>
                    <transition event="DHCPACK" target="Bound2"/>
                </state>
                <transition target="first2.thang"/>
            </state>
            <state id="first2.thang">
                <transition target="_junction.1"/>
            </state>
        </state>
        <state id="second">
            <state id="second.thing">
                <transition target="second.thang"/>
            </state>
            <state id="second.thang">
                <transition event="payment" target="_choice.1_"/>
                <transition target="_junction.1"/>
                <transition target="second.thing"/>
            </state>
        </state>
    </parallel>
    <final id="final">
    </final>
    <state id="_choice.1_">
        <transition cond="no" target="_junction.1"/>
        <transition cond="yes" target="removed"/>
    </state>
    <state id="removed">
        <transition target="final"/>
    </state>
</scxml>

**Comment by edbek** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<scxml xmlns="http://www.w3.org/2005/07/scxml" initial="_fork.1" version="1.0">
    <state id="_fork.1">
        <transition target="thing"/>
        <transition target="second.thing"/>
        <transition target="thing1"/>
    </state>
    <state id="_junction.1">
        <transition target="final"/>
    </state>
    <parallel id="bla.parallel">
        <state id="first">
            <state id="thing">
                <transition target="first.thang"/>
            </state>
            <state id="first.thang">
                <transition target="_junction.1"/>
            </state>
        </state>
        <state id="first2">
            <state id="thing1">
                <transition target="thing2"/>
                <transition target="first2.thang"/>
            </state>
            <state id="thing2" initial="Bound2">
                <history id="NormalMode2.history">
                </history>
                <state id="Bound2">
                    <onentry>dhcp_set_timers</onentry>
                    <onentry>dhcp_display_result</onentry>
                    <transition event="T1" target="Renewing2"/>
                    <transition event="10s" target="Renewing2"/>
                    <transition event="DHCPOFFER DHCPACK DHCPNACK" target="Bound2"/>
                </state>
                <state id="Renewing2">
                    <onentry>dhcp_send_request</onentry>
                    <transition event="DHCPACK" target="Bound2"/>
                </state>
                <transition target="first2.thang"/>
            </state>
            <state id="first2.thang">
                <transition target="_junction.1"/>
            </state>
        </state>
        <state id="second">
            <state id="second.thing">
                <transition target="second.thang"/>
            </state>
            <state id="second.thang">
                <transition event="payment" target="_choice.1_"/>
                <transition target="_junction.1"/>
                <transition target="second.thing"/>
            </state>
        </state>
    </parallel>
    <final id="final">
    </final>
    <state id="_choice.1_">
        <transition cond="no" target="_junction.1"/>
        <transition cond="yes" target="removed"/>
    </state>
    <state id="removed">
        <transition target="final"/>
    </state>
</scxml>`

**Comment by edbek** [comment]
here is a draft of the SCXML file.

**Comment by dziegel** [comment]
Issue is that "parallel" is not supported
